{% set name = "cluster-lensing" %}
{% set version = "0.1.2" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': 'ed1474701aac80648c4483f8e66af2663c2be1493e7a003e08e4a9f594dfa6b9'

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - astropy-base
    - scipy
    - pandas

test:
  requires:
    - python {{ python_min }}
  imports:
    - clusterlensing

about:
  home: http://github.com/jesford/cluster-lensing
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Galaxy Cluster and Weak Lensing Tools
  description: |
    This package includes tools for calculating a variety of galaxy cluster
    properties, as well as mass-richness and mass-concentration scaling
    relations, and weak lensing profiles. These include surface mass density
    (Sigma) and differential surface mass density (DeltaSigma) for NFW halos,
    both with and without the effects of cluster miscentering.
  doc_url: http://jesford.github.io/cluster-lensing/
  dev_url: http://github.com/jesford/cluster-lensing

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
