travis:
  secure:
    BINSTAR_TOKEN: VUkIv5HWeqAPs5/rmlUfM8zUpoxmRWl5Rj9YMEpXZqhGIYaUOspjQUPVOx1l5Z7WjVf4M/O5zkNgGscHiEwZYTJDSHmEoVPdGFBRUUxKzJVGr24twMpSZJovA0iZsXit0JDYSgSdPrFIJ/mJ1942MFGfBWgXkAmvgamdbbzHb8TgvP3wi9Ir591hxetMRdL0IW+BGShX4KQOxn1wzEEU0f1BfobOvbG/w4wazF34z4sf9noMFSJMhiiqtm99u8ycx1J/E3I0f9/3fetADOxT0tnLbgiRTYQ6hpbiPtIvScIX0hkNbELjmzAl5iq9C2ztJTCpeNbQgfenXrWt3e7yotOY3/3pbQCMnylY+FOtnojk6Fn8CPdyEVApCRR/kQkIfDQXWyVI1QMvnFIOpQxoRYdA2d+rak2X+iqUcwldR3kYnw01/nn/MPHmp9fVX3LyrOt+wWnH/07KiyEEUXIioSjNupC5yxS0nb0cTBOqwRIZ0JFD5Lt4UhpAmG0DwJkeHgJngOUMOrtH1O1GErEfdYRZsFE++gyD6S16fSIKjgo5p3RNnJsHn3V+q93ziu/PcLUtZzU3LZrNsTF4NFjY52LEAObMBpLY6JJHicaafPSGGhGaH4CppfrALPBzniDgxFkma98eDvZZsNtnvTs3UE/FKupf8LHtVqmGDMxRcUw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
